feat(prompt): output to stderr instead of stdout
c4spar/deno-cliffy pull request #419
Opened 2022-08-10 22:24 UTC by crooke

The rationale is that using stderr allows you to chain actual command output together with pipes. I updated `examples/prompt/input.ts` to demonstrate what I mean. Putting prompt output on stderr allows you to pipe the JSON body to stdout for use with other tools, like `jq`:
```bash
$ ./examples/prompt/input.ts | jq .name
 ? What's your github user name? › crooke
"Eric Crook"
```
Otherwise, the prompt output will get piped into `jq` and the terminal will be blank and appear to hang.

2022-08-13 14:29 UTC, c4spar requested changes
Hi @crooke, thx for the PR!

But I'm not sure if we should write to stderr by default, because it's not an error output. I think it would make more sense to make it configurable for all prompts, so you can change it to stderr if it makes sense.

```ts
await Input.prompt({
  message: "foo bar...",
  stdout: Deno.stderr,
});
```

I also took a look at the npm packages inquirer, enquirer and prompts and they all write to stdout by default.

Another idea could be to write to stderr by default only if `stdout` is not a `tty` 🤔 `stdout = Deno.isatty(Deno.stdout.rid) ? Deno.stdout : Deno.stderr`. But i'm also not sure if this is a good default.

Would you like to make it configurable @crooke?

2022-08-15 00:59 UTC, crooke commented
> Hi @crooke, thx for the PR!
> 
> But I'm not sure if we should write to stderr by default, because it's not an error output. I think it would make more sense to make it configurable for all prompts, so you can change it to stderr if it makes sense.
> 
> ```ts
> await Input.prompt({
>   message: "foo bar...",
>   stdout: Deno.stderr,
> });
> ```
> 
> I also took a look at the npm packages inquirer, enquirer and prompts and they all write to stdout by default.
> 
> Another idea could be to write to stderr by default only if `stdout` is not a `tty` 🤔 `stdout = Deno.isatty(Deno.stdout.rid) ? Deno.stdout : Deno.stderr`. But i'm also not sure if this is a good default.
> 
> Would you like to make it configurable @crooke?

I think stderr is conventionally used for errors _or_ diagnostics. [This](https://unix.stackexchange.com/q/331611) StackExchange question has a good discussion on it. However, I guess a prompt like this doesn't necessarily fall into either category, so I'm fine with making it configurable. I'll work on that.

2022-08-15 08:45 UTC, c4spar commented
>  I think stderr is conventionally used for errors or diagnostics.

I totally agree with you and `ffmpeg` is a good example. It logs everything to stderr, only the binary output goes to stdout. But I think we should let the user of cliffy decide if he wants to log to stderr instead of stdout. But i'm open for discussion to change the default.

2023-02-25 21:57 UTC, c4spar commented
I'm willing to reconsider the defaults, but I'd like to hear more feedback from more people first. I have created an issue for this #552.

2023-03-25 11:54 UTC, c4spar commented
I will close this PR now. I made the input and output configurable but i will keep stdout the default.
But thx for your PR @crooke!
Feel free to open a new PR with with your updated input example!

2023-03-25 11:54 UTC, closed without merging