feat: add built-in `jsr` upgrade provider (rework)
c4spar/deno-cliffy pull request #692
Opened 2024-04-07 21:06 UTC by JOTSR

# Summary

Add buit-in support of [jsr](https://jsr.io/) as upgrade provider.
Rework of #687 from main branch (deleting all changes from #679).

# Motivation

Allow to seamlessly upgrade [jsr](https://jsr.io/) hosted cli.

# Changes

- Add `upgrade/provider/jsr.ts`.
- Missing update of [examples/command/upgrade_command.ts](examples/command/upgrade_command.ts) as it relies on non `jsr` package (need discussion/improvement).

2024-04-07 22:14 UTC, JOTSR commented
Cliffy actually assume that the name to the module to install is by default `${name}.ts` in the builtin upgrade command.
```ts
async upgrade(
    { name, from, to, importMap, main = `${name}.ts`, args = [] }:
      UpgradeOptions,
  ): Promise<void>
```
However `jsr` package can use "custom" exports and a cli from this repository can be loaded from `jsr:@scope/name` or `jsr:@scope/name/extensionless_path`. Do you think that the default value for `main: string | undefined` can be:
1. Leave to `undefined`
2. Leave to `${name}`
3. Leave to `${name}.ts` (legacy)

for only `jsr` source in order to avoid supplementary configuration as for others providers ?

eg:
```ts
// deno.json
{
  "name": "@cliffy/cliffy",
  "exports":  {
    ".": "./cliffy.ts",
    "./cliffy": "./cliffy.ts"
}
```
| solution\path |                         default                        |                                exported                                |                                  private                                  |
|:-------------:|:------------------------------------------------------:|:----------------------------------------------------------------------:|:-------------------------------------------------------------------------:|
| 1             | `new JsrProvider({ scope: "cliffy", name: "cliffy" })` | `new JsrProvider({ scope: "cliffy", name: "cliffy", main: "cliffy" })` | `new JsrProvider({ scope: "cliffy", name: "cliffy", main: "cliffy.ts" })` |
| 2             | N.A.                                                   | `new JsrProvider({ scope: "cliffy", name: "cliffy" })`                 | `new JsrProvider({ scope: "cliffy", name: "cliffy", main: "cliffy.ts" })` |
| 3             | N.A.                                                   | `new JsrProvider({ scope: "cliffy", name: "cliffy", main: "cliffy" })` | `new JsrProvider({ scope: "cliffy", name: "cliffy" })`                    |

2024-04-30 20:29 UTC, c4spar requested changes
Thx for the rework @JOTSR!

2024-04-30 20:29 UTC, c4spar commented on command/upgrade/provider.ts
> +      `${registryUrl}/${name}` :
Name is already added to registryUrl by getRegistryUrl.

```suggestion
      registryUrl :
```

2024-04-30 20:29 UTC, c4spar commented on command/upgrade/upgrade_command.ts
> +        "--version <version:string>",
You removed the shell completion for the version option 😉

2024-04-30 20:33 UTC, c4spar commented on command/upgrade/provider.ts
> +      `${registryUrl}/${name}` :
or did you mean `${registryUrl}/${main}`?

2024-04-30 21:33 UTC, c4spar commented on command/upgrade/provider.ts
> +      `${registryUrl}/${name}` :
If we use the main option for jsr exports, we need to add a main option to the `Provider` constructor so we can define it differently for different providers. The provider main option would then override the upgrade command main option.

2024-05-06 08:55 UTC, JOTSR commented
@c4spar what your though for [provider config](https://github.com/c4spar/deno-cliffy/pull/692#issuecomment-2041625637) defaults ?

2024-05-08 21:09 UTC, c4spar commented
I think we can remove the default value for the main option for now. I am currently working on a refactoring of the upgrade command and may move the default value to the provider itself.

2024-05-13 22:25 UTC, c4spar approved these changes
Thx again @JOTSR! LGTM 👍

2024-05-13 22:25 UTC, merged