feat: Build help text based on terminal width, adjust column widths dynamically
c4spar/deno-cliffy pull request #761
Opened 2024-10-25 21:54 UTC by effigies

This PR adds `maxTableWidth` and `colRigidity` options to `TableSettings`, allowing the table renderer to target a particular maximum width. `colRigidity` is a parameter where `1` indicates that the column width should not be reduced, and `0` that it can be adjusted arbitrarily. I made it a number instead of a bool, since it seems plausible to allow for a `0.5` to be reduced by half the amount of a `0`, but I only implemented `0` and `1`.

I then use this to update the help text generation, which is constrained to use the terminal width as the maximum width. I make the first columns rigid, as the descriptions and types are more likely to take up space and more tolerant to line breaks.

I hope this is reasonable. It dramatically improves the help text for my tool.

<details><summary>Before (regardless of terminal width):</summary>

```
❯ deno run -A jsr:@bids/validator --help

Usage:   bids-validator <dataset_directory>
Version: 1.14.13

Description:

  This tool checks if a dataset in a given directory is compatible with the Brain Imaging Data Structure specification. To learn more about
  Brain Imaging Data Structure visit http://bids.neuroimaging.io

Options:

  -h, --help                              - Show this help.
  -V, --version                           - Show the version number for this program.
  --json                                  - Output machine readable JSON
  -s, --schema           <URL-or-tag>     - Specify a schema version to use for validation
  -c, --config           <file>           - Path to a JSON configuration file
  -v, --verbose                           - Log more extensive information about issues
  --ignoreWarnings                        - Disregard non-critical issues
  --ignoreNiftiHeaders                    - Disregard NIfTI header content during validation
  --debug                <level>          - Enable debug output                                                             (Default: "ERROR", Values: "NOTSET", "DEBUG", "INFO",
                                                                                                                            "WARN", "ERROR", "CRITICAL")
  --filenameMode                          - Enable filename checks for newline separated filenames read from stdin
  --blacklistModalities  <modalities...>  - Array of modalities to error on if detected.                                    (Default: [], Values: "MRI", "PET", "MEG", "EEG", "iEEG",
                                                                                                                            "Microscopy", "NIRS", "MRS")
  -r, --recursive                         - Validate datasets found in derivatives directories in addition to root dataset
  -o, --outfile          <file>           - File to write validation results to.
  --color, --no-color    [color]          - Enable/disable color output (defaults to detected support)                      (Default: true)
```

</details>
<details><summary>After (88 columns)</summary>

```
❯ deno run -A ~/Projects/bids/bids-validator/bids-validator/src/bids-validator.ts --help

Usage:   bids-validator <dataset_directory>
Version: v1.14.15-dev.0-11-g8f3519b3

Description:

  This tool checks if a dataset in a given directory is compatible with the Brain
  Imaging Data Structure specification. To learn more about Brain Imaging Data
  Structure visit http://bids.neuroimaging.io

Options:

  -h, --help                              - Show this help.
  -V, --version                           - Show the version number
                                            for this program.
  --json                                  - Output machine readable
                                            JSON
  -s, --schema           <URL-or-tag>     - Specify a schema version
                                            to use for validation
  -c, --config           <file>           - Path to a JSON
                                            configuration file
  -v, --verbose                           - Log more extensive
                                            information about issues
  --ignoreWarnings                        - Disregard non-critical
                                            issues
  --ignoreNiftiHeaders                    - Disregard NIfTI header
                                            content during
                                            validation
  --debug                <level>          - Enable debug output       (Default:
                                                                      "ERROR", Values:
                                                                      "NOTSET",
                                                                      "DEBUG", "INFO",
                                                                      "WARN", "ERROR",
                                                                      "CRITICAL")
  --filenameMode                          - Enable filename checks
                                            for newline separated
                                            filenames read from
                                            stdin
  --blacklistModalities  <modalities...>  - Array of modalities to    (Default: [],
                                            error on if detected.     Values: "MRI",
                                                                      "PET", "MEG",
                                                                      "EEG", "iEEG",
                                                                      "Microscopy",
                                                                      "NIRS", "MRS")
  -r, --recursive                         - Validate datasets found
                                            in derivatives
                                            directories in addition
                                            to root dataset
  -o, --outfile          <file>           - File to write validation
                                            results to.
  --color, --no-color    [color]          - Enable/disable color      (Default: true)
                                            output (defaults to
                                            detected support)
```

</details>

<details><summary>142 columns</summary>

```
❯ deno run -A ~/Projects/bids/bids-validator/bids-validator/src/bids-validator.ts --help

Usage:   bids-validator <dataset_directory>
Version: v1.14.15-dev.0-11-g8f3519b3

Description:

  This tool checks if a dataset in a given directory is compatible with the Brain Imaging Data Structure specification. To learn more about
  Brain Imaging Data Structure visit http://bids.neuroimaging.io

Options:

  -h, --help                              - Show this help.
  -V, --version                           - Show the version number for this program.
  --json                                  - Output machine readable JSON
  -s, --schema           <URL-or-tag>     - Specify a schema version to use for validation
  -c, --config           <file>           - Path to a JSON configuration file
  -v, --verbose                           - Log more extensive information about issues
  --ignoreWarnings                        - Disregard non-critical issues
  --ignoreNiftiHeaders                    - Disregard NIfTI header content during validation
  --debug                <level>          - Enable debug output                                      (Default: "ERROR", Values: "NOTSET",
                                                                                                     "DEBUG", "INFO", "WARN", "ERROR",
                                                                                                     "CRITICAL")
  --filenameMode                          - Enable filename checks for newline separated filenames
                                            read from stdin
  --blacklistModalities  <modalities...>  - Array of modalities to error on if dete [...]

2024-10-25 21:57 UTC, effigies commented
I think this closes #723. It doesn't enable configuration, but it does do what I think they want. It's certainly what I want.

If someone wants to try this out, you can replace `@cliffy/command` with `@effigies/cliffy-command@1.0.0-dev.7` and `@cliffy/table` with `@effigies/cliffy-table@1.0.0-dev.4`.

2025-01-08 21:15 UTC, effigies commented
@c4spar Just checking in to see if there's any interest in this patch. Happy to adjust to suit the needs/conventions of the project.

2025-01-15 04:52 UTC, brad-jones commented
I tried out your packages @effigies it certainly helps when the terminal is narrow but when it is wide it would be nice if it made use of the space.

Unless I'm missing something this still caps the max width at 150?
`this.width = Math.min(Deno.consoleSize().columns, 150);`

Here is an example:

```
  -s, --stage      <stage>      - The Xero stage or environment name to connect to.  (required, Values: "test", "test-dev", "uat", "uat-dev",
                                                                                     "prod")                                                 
  -r, --region     <region>     - The AWS Region the cluster resides in.             (Default: "based on stage:                              
                                                                                     test=ap-southeast-2,uat=us-west-2,prod=us-east-1")  
```

I'd prefer something like

```
  -s, --stage      <stage>      - The Xero stage or environment name to connect to.  (required, Values: "test", "test-dev", "uat", "uat-dev", "prod")
  -r, --region     <region>     - The AWS Region the cluster resides in.             (Default: "based on stage: test=ap-southeast-2,uat=us-west-2,prod=us-east-1")
```

If the terminal supports it.

Another option might be to put the hints below the option.

```
  -s, --stage      <stage>      - The Xero stage or environment name to connect to.
                                (required, Values: "test", "test-dev", "uat", "uat-dev", "prod")

  -r, --region     <region>     - The AWS Region the cluster resides in.
                               (Default: "based on stage: test=ap-southeast-2,uat=us-west-2,prod=us-east-1")
```

2026-02-15 20:15 UTC, c4spar requested changes
Thx for the PR @effigies and sry for the very late response!!

The feature is definitly welcome!
Are you still interested in getting this merged?

I added a view comments.

2026-02-15 20:15 UTC, c4spar commented on command/help/_help_generator.ts
> +      this.width = Math.min(Deno.consoleSize().columns, 150);
We should use `getColumns()` from `@cliffy/internal/runtime/get-columns` here.

2026-02-15 20:15 UTC, c4spar commented on table/table.ts
> +  colRigidity: number | Array<number>;
I think `flexShrink` would be a better name, then we could add `flexGrow` later as well.

2026-04-24 19:43 UTC, effigies commented
Oh sorry, let me see if I can fix this up real quick this afternoon. I have very limited time next week.

2026-04-24 20:32 UTC, effigies commented
Okay, I think I've addressed this, except I'm not sure how to actually wire up the `flexShrink` in the columns, so right now it's just a getter/setter.

2026-04-25 13:38 UTC, c4spar commented
awesome thank you! I will have a look.

2026-04-25 18:11 UTC, c4spar approved these changes
Thx again @effigies, looks good to me now! I also made some improvements to correctly handle padding, border, and minColWidth. I've enabled flexShrink by default so maxTableWidth works out of the box — but it only activates when maxTableWidth is finite, which defaults to Infinity. I've also renamed maxTableWidth to maxWidth.

2026-04-25 18:18 UTC, merged